name: Poll Amtrak (NYP) → Drive

on:
  schedule:
    # Hourly off-peak at :02 UTC, excluding peak windows (mirror NJT timing, lightly staggered)
    - cron: "2 0-10,14-19,23 * * *"

    # AM peak 07:00–09:59 ET → 11:00–13:59 UTC (every 15 min, +2 min stagger)
    - cron: "2,17,32,47 11-13 * * *"

    # PM peak 16:30–18:30 ET → 20:30–22:30 UTC (every 15 min, +2 min stagger)
    - cron: "2,17,32,47 20-21 * * *"
    - cron: "2,17,32 22 * * *"

  workflow_dispatch: {}

concurrency:
  group: poll-amtrak-append
  cancel-in-progress: false

jobs:
  poll:
    runs-on: ubuntu-latest
    permissions: { contents: read }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install rclone
        run: curl -fsSL https://rclone.org/install.sh | sudo bash

      - name: Configure rclone
        env:
          RCLONE_CONF_B64: ${{ secrets.RCLONE_CONF_B64 }}
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONF_B64" | base64 -d > ~/.config/rclone/rclone.conf
          chmod 600 ~/.config/rclone/rclone.conf
          echo "[ok] rclone.conf installed"

      - name: Ensure local/remote dirs
        env:
          GDRIVE_REMOTE_NAME: ${{ secrets.GDRIVE_REMOTE_NAME }}
          GDRIVE_DIR_AMTRAK: ${{ vars.GDRIVE_DIR_AMTRAK || 'penn-station/amtrak' }}
        run: |
          mkdir -p data/amtrak
          rclone mkdir "${GDRIVE_REMOTE_NAME}:${GDRIVE_DIR_AMTRAK}/raw" || true

      - name: Add poller (if not committed)
        run: |
          mkdir -p pollers
          if [ ! -f pollers/poll_amtrak.py ]; then
            cat > pollers/poll_amtrak.py <<'PY'
# (paste the entire Python script from above)
PY
            chmod +x pollers/poll_amtrak.py
          fi

      - name: Poll & append Amtrak (NYP)
        env:
          GDRIVE_REMOTE_NAME: ${{ secrets.GDRIVE_REMOTE_NAME }}
          GDRIVE_DIR_AMTRAK: ${{ vars.GDRIVE_DIR_AMTRAK || 'penn-station/amtrak' }}
          AMTRAK_MASTER_NAME: ${{ vars.AMTRAK_MASTER_NAME || 'amtrak_penn_master.csv' }}
          AMTRAK_STATION_CODE: "NYP"
        run: python3 pollers/poll_amtrak.py
